version: "3"
services:
  Jackett:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: Jackett
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_DATA_HOME=/config
      - XDG_CONFIG_HOME=/config
    hostname: 7a7ab68fc7c4
    image: linuxserver/jackett:latest
    ipc: private
    labels:
      build_version: 'Linuxserver.io version:- v0.16.1819-ls20 Build-date:- 2020-10-19T06:07:16+00:00'
      maintainer: thelamer
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:04
    networks:
      bridge:
        aliases:
    ports:
      - 32999:9117/tcp
    restart: unless-stopped
    volumes:
      - /docker_data/:/config
      - /share/winserv/Black_Hole:/hole
networks:
  bridge:
    external: true
